package chess;

import java.util.*;

/**
 * For a class that can manage a chess game, making moves on a board
 * <p>
 * Note: You can add to this class, but you may not alter
 * signature of the existing methods.
 */
public class ChessGame {
    private ChessBoard board;

    public ChessGame() {
        board = new ChessBoard();
        board.resetBoard();
    }

    /**
     * @return Which team's turn it is
     */
    public TeamColor getTeamTurn() {
        return board.getTurn();
    }

    /**
     * Set's which teams turn it is
     *
     * @param team the team whose turn it is
     */
    public void setTeamTurn(TeamColor team) {
        board.setTurn(team);
    }

    /**
     * Enum identifying the 2 possible teams in a chess game
     */
    public enum TeamColor {
        WHITE,
        BLACK
    }

    /**
     * Gets a valid moves for a piece at the given location
     *
     * @param startPosition the piece to get valid moves for
     * @return Set of valid moves for requested piece, or null if no piece at
     * startPosition
     */
    public Collection<ChessMove> validMoves(ChessPosition startPosition) {
        ChessPiece piece = board.getPiece(startPosition);
        Collection<ChessMove> moves = piece.pieceMoves(board, startPosition);
        Collection<ChessMove> confirmedMoves = new HashSet<>();
        TeamColor turn = board.getPiece(startPosition).getTeamColor();
        for (ChessMove move : moves) {
            ChessBoard testBoard = new ChessBoard(board);
            testBoard.setTurn(turn);
            ChessGame testGame = new ChessGame();
            testGame.setBoard(testBoard);
            try {
                testGame.makeMove(move);
                if (testGame.board.isInCheck(turn)) continue;
                else confirmedMoves.add(move);
            } catch (InvalidMoveException e) {
                continue;
            }
        }
        return confirmedMoves;
    }

    /**
     * Makes a move in a chess game
     *
     * @param move chess move to preform
     * @throws InvalidMoveException if move is invalid
     */
    public void makeMove(ChessMove move) throws InvalidMoveException {
        // If game over. throw
//        board.printBoard();
        ChessPosition start = move.getStartPosition();
        ChessPosition end = move.getEndPosition();
        ChessPiece piece = board.getPiece(move.getStartPosition());
        if (piece == null) throw new InvalidMoveException("No piece at location: " + move.getStartPosition());
        TeamColor teamColor = piece.getTeamColor();
        if (teamColor != board.getTurn()) throw new InvalidMoveException("Not " + teamColor + "'s turn.");
        Collection<ChessMove> moves = piece.pieceMoves(board, start);
        if (!moves.contains(move)) throw new InvalidMoveException(move + " is an invalid move");
        // update move to be the version generated by ChessPiece so that the annotations are available
        ChessMove flaggedMove = null;
        for (ChessMove flagged : moves) {
            if (Objects.equals(move.getEndPosition(), flagged.getEndPosition()) &&
                    Objects.equals(move.getPromotionPiece(), flagged.getPromotionPiece())
            ) {
                flaggedMove = flagged;
                break;
            }
        }
        if (flaggedMove == null) throw new InvalidMoveException("Move wasn't in set of generated valid moves");
        // Test for check
        ChessGame testGame = new ChessGame();
        ChessBoard testBoard = new ChessBoard(board);
        testGame.setBoard(testBoard);
        testGame.executeMove(flaggedMove);
        if (testGame.isInCheck(teamColor)) throw new InvalidMoveException(move + " puts the king in check");
        executeMove(flaggedMove);
//        board.printBoard();
    }

    private void executeMove(ChessMove move) {
        ChessPiece piece = move.getPiece();
        ChessPosition start = move.getStartPosition();
        TeamColor teamColor = move.getTeam();
        int homeRank = (teamColor == TeamColor.WHITE) ? 1 : 8;
        // Castling
        if (move.isCastle()) {
            ChessPiece castledRook = board.removePiece(move.getCastlingRookPosition());
            board.addPiece(move.getNewCastlingRookPosition(), castledRook);
        }
        // Remove Castling flags after moving king or rook
        if (piece.getPieceType() == ChessPiece.PieceType.ROOK && start.getRank() == homeRank) {
            if (start.getFile() == 1) {
                if (teamColor == TeamColor.WHITE) board.whiteCanCastleLong(false);
                else board.whiteCanCastleShort(false);
            }
            if (start.getFile() == ChessBoard.BOARD_SIZE) {
                if (teamColor == TeamColor.WHITE) board.whiteCanCastleLong(false);
                else board.whiteCanCastleShort(false);
            }
        }
        if (piece.getPieceType() == ChessPiece.PieceType.KING) {
            if (teamColor == TeamColor.WHITE) {
                board.whiteCanCastleShort(false);
                board.whiteCanCastleLong(false);
            } else {
                board.blackCanCastleShort(false);
                board.blackCanCastleLong(false);
            }
        }
        // En Passant rules
        ChessPiece capturedPiece = move.getCapturedPiece();
        // Capture by en passant
        if (capturedPiece != null && move.getCapturedPiece().getPieceType() == ChessPiece.PieceType.EN_PASSANT) {
            board.removePiece(board.getPassedPawn());
        }
        // clear old ghost values
        board.clearEnPassant();
        // Add ghost piece to board on leap
        if (move.isLeap()) {
            board.addPiece(move.getPositionSkippedByLeap(), new ChessPiece(move.getTeam(), ChessPiece.PieceType.EN_PASSANT));
            board.setPassedPawn(move.getEndPosition());
            board.setEnPassantTarget(move.getPositionSkippedByLeap());
        }
        // remove piece from starting position
        board.removePiece(move.getStartPosition());
        // update piece if promoted
        if (move.getPromotionPiece() != null) piece = new ChessPiece(teamColor, move.getPromotionPiece());
        // add back (replaces existing values like they were removed)
        board.addPiece(move.getEndPosition(), piece);
        setTeamTurn(otherTeam(board.getTurn()));
    }

    /**
     * Determines if the given team is in check
     *
     * @param teamColor which team to check for check
     * @return True if the specified team is in check
     */
    public boolean isInCheck(TeamColor teamColor) {
        return getSquaresThreatenedBy(otherTeam(teamColor)).contains(getKingPosition(teamColor));
    }

    /**
     * Determines if the given team is in checkmate
     *
     * @param teamColor which team to check for checkmate
     * @return True if the specified team is in checkmate
     */
    public boolean isInCheckmate(TeamColor teamColor) {
        Collection<ChessMove> moves = new HashSet<>();
        board.getPositionsFor(teamColor).forEach(position ->
                moves.addAll(validMoves(position))
        );
        return isInCheck(teamColor) && moves.isEmpty();
    }

    /**
     * Determines if the given team is in stalemate, which here is defined as having
     * no valid moves
     *
     * @param teamColor which team to check for stalemate
     * @return True if the specified team is in stalemate, otherwise false
     */
    public boolean isInStalemate(TeamColor teamColor) {
        Collection<ChessMove> moves = new HashSet<>();
        board.getPositionsFor(teamColor).forEach(position ->
                moves.addAll(validMoves(position))
        );
        return !isInCheck(teamColor) && moves.isEmpty();
    }

    /**
     * Sets this game's chessboard with a given board
     *
     * @param board the new board to use
     */
    public void setBoard(ChessBoard board) {
        this.board = board;
    }

    /**
     * Gets the current chessboard
     *
     * @return the chessboard
     */
    public ChessBoard getBoard() {
        return board;
    }

    private Collection<ChessPosition> getSquaresThreatenedBy(TeamColor color) {
        HashSet<ChessPosition> threatenedSquares = new HashSet<>();
        board.getPieces(color).forEach((position, piece) ->
                piece.pieceMoves(board, position).forEach(move ->
                        threatenedSquares.add(move.getEndPosition())
                )
        );
        return threatenedSquares;
    }

    private ChessPosition getKingPosition(TeamColor color) {
        HashMap<ChessPosition, ChessPiece> pieces = board.getPieces(color);
        for (Map.Entry<ChessPosition, ChessPiece> position : board.getPieces(color).entrySet()) {
            if (position.getValue().getPieceType() == ChessPiece.PieceType.KING) {
                return position.getKey();
            }
        }
        return null;
    }

    private TeamColor otherTeam(TeamColor color) {
        return color == TeamColor.WHITE ? TeamColor.BLACK : TeamColor.WHITE;
    }
}
